import { Injectable, signal } from '@angular/core';
import { Empleado, Equipo } from '../../shared/interfaces/Empleado.interface';
import { Fichaje } from '../../shared/interfaces/Fichaje.interface';

@Injectable({
  providedIn: 'root'
})
export class MockService {

  empleados: Empleado[] = [
    {
      id: 1,
      ccc: '12345678901234',
      foto: '',
      nombre: 'Laura',
      apellidos: 'Martínez Murcia',
      calendario: 'General',
      dni: '12345678A',
      telefono: '600123456',
      email: 'laura.martinez@empresa.com',
      fechaNacimiento: '1990-04-15',
      genero: 'F',
      convenio: 'Convenio Oficinas',
      horario: '08:00 - 16:00',
      tipoContrato: 'Indefinido',
      contratoDesde: new Date('2020-01-01'),
      indefinido: true,
      centro: 'Madrid',
      puesto: 'Administrativa',
      politicaVacaciones: 'Natural',
      frecuenciaFirma: 'Diaria',
      notificaciones: true,
      metodoValidacion: 'email',
      permisosPorDefecto: 'empleado',
      permisosExtra: '',
      bajaIndefinida: false,
      activo: true,
      metodos: {
        appMovil: true,
        appWeb: true,
        telefono: false,
        email: true,
      },
      marcarInicio: true,
      geolocalizable: true,
      permitirCorreccion: false,
      permitirHorasExtra: false,
    },
    {
      id: 2,
      ccc: '98765432109876',
      foto: '',
      nombre: 'Carlos',
      apellidos: 'Ruiz Fernández',
      calendario: 'Turnos rotativos',
      dni: '87654321B',
      telefono: '699765432',
      email: 'carlos.ruiz@empresa.com',
      fechaNacimiento: '1985-11-22',
      genero: 'M',
      convenio: 'Convenio Industria',
      horario: '06:00 - 14:00',
      tipoContrato: 'Temporal',
      contratoDesde: new Date('2024-02-15'),
      indefinido: false,
      centro: 'Barcelona',
      puesto: 'Operario de fábrica',
      politicaVacaciones: 'Días hábiles',
      frecuenciaFirma: 'Semanal',
      notificaciones: false,
      metodoValidacion: 'app',
      permisosPorDefecto: 'operario',
      permisosExtra: 'ver parte diario',
      bajaIndefinida: false,
      activo: true,
      metodos: {
        appMovil: true,
        appWeb: false,
        telefono: true,
        email: false,
      },
      marcarInicio: false,
      geolocalizable: false,
      permitirCorreccion: true,
      permitirHorasExtra: true,
    }
  ];

  equipos: Equipo[] = [
    { id: 1, nombre: 'Administración', empleados: [] },
    { id: 2, nombre: 'Marketing', empleados: [] },
  ];

  empleadoEjemplo1: Empleado = {
    id: 1,
    ccc: '12345678901234',
    foto: '',
    nombre: 'Laura',
    apellidos: 'Martínez García',
    calendario: 'Calendario 1',
    dni: '12345678A',
    telefono: '600123456',
    email: 'laura@example.com',
    fechaNacimiento: '1990-05-10',
    genero: 'mujer',
    convenio: 'Convenio A',
    horario: '09:00 - 17:00',
    tipoContrato: 'Indefinido',
    contratoDesde: new Date('2022-01-15'),
    indefinido: true,
    centro: 'Oficina Central',
    puesto: 'Administrativa',
    politicaVacaciones: 'Estándar',
    frecuenciaFirma: 'Diaria',
    notificaciones: true,
    metodoValidacion: 'Manual',
    permisosPorDefecto: 'Ninguno',
    permisosExtra: '',
    bajaIndefinida: false,
    activo: true,
    metodos: {
      appMovil: true,
      appWeb: true,
      telefono: false,
      email: false,
    },
    marcarInicio: false,
    geolocalizable: true,
    permitirCorreccion: true,
    permitirHorasExtra: false,
  };

  empleadoEjemplo2: Empleado = {
    ...this.empleadoEjemplo1,
    id: 2,
    nombre: 'Pedro',
    apellidos: 'López Ruiz',
    email: 'pedro@example.com',
    telefono: '600987654',
  };

  FICHAJES_MOCK: Fichaje[] = [
    {
      id: 1,
      estado: 'Validada',
      empleado: this.empleadoEjemplo1,
      fecha: '2025-01-22',
      diaSemana: 'miércoles',
      horario: '09:00h a 14:00h',
      horasEstimadas: '8,0h',
      horasTrabajadas: '8,0h',
      balance: '0,0h',
      metodoRegistro: 'Validación de la jornada',
      geolocalizacion: true,
      geocercas: false,
    },
    {
      id: 2,
      estado: 'Corregida y validada',
      empleado: this.empleadoEjemplo2,
      fecha: '2025-01-22',
      diaSemana: 'miércoles',
      horario: '09:00h a 13:00h',
      horasEstimadas: '8,0h',
      horasTrabajadas: '7,0h',
      balance: '-1,0h',
      metodoRegistro: 'Aplicación móvil',
      geolocalizacion: false,
      geocercas: false,
    },
    {
      id: 3,
      estado: 'Validada',
      empleado: this.empleados[0],
      fecha: '2025-02-22',
      diaSemana: 'miércoles',
      horario: '09:00h a 14:00h',
      horasEstimadas: '8,0h',
      horasTrabajadas: '8,0h',
      balance: '0,0h',
      metodoRegistro: 'Validación de la jornada',
      geolocalizacion: true,
      geocercas: false,
    },
    {
      id: 4,
      estado: 'Validada',
      empleado: this.empleados[1],
      fecha: '2026-03-22',
      diaSemana: 'miércoles',
      horario: '09:00h a 14:00h',
      horasEstimadas: '8,0h',
      horasTrabajadas: '8,0h',
      balance: '0,0h',
      metodoRegistro: 'Validación de la jornada',
      geolocalizacion: true,
      geocercas: false,
    }
  ];



}
